# tests/runtests.jl
#
# Top-level test runner for BUGJulia.
# Run with: sbatch scripts/run_julia.sbatch tests/runtests.jl
#
# There is exactly ONE integrator, `bond_update_bug!` (the discarded-projector
# 2r-Galerkin BUG), and this file covers all of it. Every other BUG scheme --
# the faithful-KLS kernel, the global-sweep discarded BUG, the ITensors tree --
# has been deleted; the pre-consolidation code remains only in the git tag
# `archive/pre-bond-update-legacy`.

using Test
using LinearAlgebra
import Random
Random.seed!(42)          # the integrator seeds its own RNG from BondUpdateOptions

@testset "BondUpdateBUG" begin
    # building blocks, in dependency order
    include("BondUpdateBUG/test_symmetric_mps.jl")
    include("BondUpdateBUG/test_frame.jl")
    include("BondUpdateBUG/test_expv.jl")
    include("BondUpdateBUG/test_sectors.jl")
    include("BondUpdateBUG/test_augment.jl")
    include("BondUpdateBUG/test_gates.jl")
    include("BondUpdateBUG/test_kls_step.jl")
    include("BondUpdateBUG/test_sweep.jl")
    include("BondUpdateBUG/test_driver.jl")
end

@testset "references" begin
    # the two independent references, each validated before being relied on
    include("common/test_dense_reference.jl")
end

@testset "validation" begin
    include("BondUpdateBUG/test_heisenberg_l6_reference.jl")
    include("BondUpdateBUG/test_xx_analytic.jl")
end

@testset "crosscheck" begin
    # Parity against the verified Alice kernel. Needs
    # tests/crosscheck/reference_l6_heisenberg.json, which is regenerated by
    # scripts/run_python.sbatch tests/crosscheck/export_python_reference.py
    include("crosscheck/test_python_parity.jl")
end
